version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: konada
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./my-mysql-data:/var/lib/mysql
  app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8080:8080"
   environment:
     SPRING_PROFILES_ACTIVE: 'dev'
   depends_on:
     - db

volumes:
  my-mysql-data:
