version: '3.8'

services:
  db:
    image: mysql:8.0 # Or your preferred version
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: konada
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306' # Expose MySQL port to the host
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./my-mysql-data:/var/lib/mysql # Named volume for persistence

volumes:
  my-mysql-data:

