spring:
  datasource:
    url: jdbc:mysql://main-rds.ckvdyt7jwtsr.ca-central-1.rds.amazonaws.com:3306/mydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate  # 프로덕션에서는 일반적으로 'validate'를 사용
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false  # 프로덕션에서는 일반적으로 SQL 포맷팅을 끔