spring:
  datasource:
    url: ${POSTING_DB_URL_DEVELOPMENT}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${POSTING_DB_USERNAME}
    password: ${POSTING_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false