
server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true #??? ?? ?? ??

spring:
    datasource: ##db??
        url: jdbc:mysql://localhost:3307/kon
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
        multipart: ##?? ??? ??
            max-file-size: 3000MB
            max-request-size: 3100MB
    jpa: ##jpa ??
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    output: ##??? ????
        ansi:
            enabled: always

logging: #log-level
    level:
        root: info
        web: info
        sql: debug
