 Development, Production
spring:
  datasource:
    url: ${POSTING_DB_URL_PRODUCTION}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${POSTING_DB_USERNAME}
    password: ${POSTING_VALIDATE}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate  # production, development
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false   # production, development

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/konada?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: user
#    password: userpassword
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update # or use 'create' to create the schema on startup, 'validate' to validate the schema, none to do nothing.
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
