name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get current time
        id: current-time
        run: echo "::set-output name=formattedTime::$(date +%Y-%m-%d-%H-%M-%S)"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t sample:${{steps.current-time.outputs.formattedTime}} .
          docker tag sample:${{steps.current-time.outputs.formattedTime}} xxx.dkr.ecr.ca-central-1.amazonaws.com/sample:${{steps.current-time.outputs.formattedTime}}
          docker push xxx.dkr.ecr.ca-central-1.amazonaws.com/sample:${{steps.current-time.outputs.formattedTime}}
